### ISSUE TITLE
Discussion about the initial requirements

### ISSUE THREAD

**Issue by yousafanwar** [yousafanwar/Recruitzi#1]
Initial objectives:

1- Create a database to store the worker’s profiles, it would be mandatory for the workers to add some keywords specific to their skills. With my current skillset, I would create objects to store the profiles but I think that would compromise the efficiency in a real project if we were to store a large number of profiles that may need continuous alterations.

2- A client contacts the Recruitzi by filling out a form, providing the keywords and then those keywords are used to filter out the workers.

3- A generic message is then sent to the filtered workers with the date and time provided by the clients and depending on their response they would be selected.  

Once these 3 objectives have been obtained then we'll move towards the remaining tasks.

**Comment by akiftariq** [comment]
Well, there are many ways a project can be started. Usually every software project starts with a "Problem Statement" which I have already shared with you in the PDF document.

Before choosing your tools, you should identify the **users** involved in the system you are going to build/design. There are three main users of the system:

1. Agency/Staffing company (for whom you are creating the system)
2. Client (Staffing company's client who is going to order temp workers for some event)
3. Workers (Who are willing to work for temp jobs)

With this in mind, in the first step, you can create a system diagram for a visual representation of your system. But that is not a necessary step since it is going to help you to visualize the system.

I think what you should do next is to draw an entity relationship diagram or simple called database diagram. (reference: https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model). This will help you document the design of your database. But before that you have to have a basic understanding of relational database.

I think we can have a call about it. I can explain the basics, so you don't have to look here and there. The problem with finding help about topics from the Internet, that you don't know is that you find a lot of unnecessary information too, and you don't know what you need right now and what you can ignore.

**Comment by yousafanwar** [comment]
I have created an ER diagram, furthermore, I have created a basic database for this project according to the ER. So far I have created four tables, one for each entity and an Event table. I have uploaded the SQL files of each of the tables. 
Kindly take a look at the files and let me know how to proceed further. 

ER link: https://drive.google.com/file/d/1XpTK_IeD8i7QHyQJo7MC87PSFtpSXLqg/view?usp=sharing

**Comment by yousafanwar** [comment]
I have a few questions.

Q1) What is the significance of adding start and end time in query method of db.js file? 
Q2) In which scenarios do we use res.send() and res.json()? (My understanding is that res.json() is used whenever we are interacting with the database where we want a json response)
Q3) What is the purpose of using express.Router() in the project? 
Q4) Referring to express.Router section, what is router.use((req, res, next) method? (REF: https://expressjs.com/en/guide/routing.html)

**Comment by akiftariq** [comment]
Please close this issue. We don't need to work in the scope of this one.
